[project]
name = "shopee-rodizio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Enzo Consulo", email = "enzoconsulo@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
shopee-rodizio = "shopee_rodizio:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]

[tool.ruff]
target-version = "py312"
line-length = 100
